### ISSUE TITLE
Lab PDF file not found

### ISSUE THREAD

**Issue by Vincent4AI** [rightingcode/rightingcode.github.io#1]
Hi:
    Thanks for this amazing course first. But in the lab page, the assignments file is not found, like this link http://rightingcode.org/assignments/1.pdf .

**Comment by Vincent4AI** [comment]
Another issues is in reading page some lessons document is lack from lesson 4

**Comment by Roadsong** [comment]
It seems that they do not have any update since then...

Does anyone have alternative of any COMPLETED program analysis course?

The video is great, BTW.

**Comment by XujieSi** [comment]
@KunPengRen @Roadsong Thanks for being interested in this course. An improved version of this course will be available on Coursera soon.
